package main

func main() {

	// fmt.Println("hello world")

	// Echo()
	// TestPrint()
	// Echo2()
	// Echo3()
	// P1_1()
	// P1_2()
	// Dup1()
	// Dup2()
	// Dup3()
	// ShowLissajous()
	// P1_5()
	// Fetch()
	// P1_8()
	// P1_9()
	// FetchAll()
	// Server1()
	// Server2()
	// Server3()
	// P1_12()
	// C2UseConst()
	// C2UsePtr()
	// C2Echo4()
	// C2UseFlag()
	// C2UseType()
	// C3UseBit()
	// C3UseFor()
	// C3UsePrint()
	// C3Surface()
	// C3UseBool()
	// C3UseUtf8()
	// C3PrintInts()
	// C3UseConst()
	// C4UseArray()
	// C4P4_2()
	// C4UseSlice()
	// C4UseAppendInt()
	// C4ShowSliceCapChange()
	// C4UseRemove()
	// C4UseMap()
	// C4UseJson()
	// C4Issue()
	// C5PrintFunc()
	// C5FindLink()
	// C5ErrorF()
	// C5UseRawReturn()
	// C5UseWait()
	// C5UseFunc()
	// C5UseDefer()
	// C5UsePanic()
	// C6UseMethod()
	// C6UsePath()
	// C6UseC6ColoredPoint()
	// UseC6Cache()
	// C6UseMethodVar()
	// C7UseByteCounter()
	C7UseRocket()

}
